# NumPy Indexing and Selection

In [1]:
import numpy as np

### Indexing & slicing of 1-D arrays (vectors)

In [2]:
array_1d = np.array([-10, -2, 0, 2, 17, 106,200])

In [3]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [4]:
# Getting value at certain index
array_1d[0]

-10

In [5]:
# Getting a range value
array_1d[0:3], array_1d
#array_1d is included here just for our understanding

(array([-10,  -2,   0]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [6]:
# Using -ve index 
array_1d[-2], array_1d

(106, array([-10,  -2,   0,   2,  17, 106, 200]))

In [7]:
# Using -ve index for a range 
array_1d[1:-2], array_1d

(array([-2,  0,  2, 17]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [8]:
array_1d[:2], array_1d[2:]

(array([-10,  -2]), array([  0,   2,  17, 106, 200]))

In [9]:
array_1d[0] = -102

In [10]:
array_1d
# The first element is changed to -102

array([-102,   -2,    0,    2,   17,  106,  200])

###  Indexing & slicing 2-D arrays (matrices)

Lets create an array with 24 elements using arange() and convert it to 2D matrix using "shape".<br>
*note, 6 x 4 = 24*

In [11]:
array_2d= np.arange(24)
array_2d.shape = (6,4)
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

To access any element, the general format is: <br>
* **`array_2d[row][col]`** <br>or<br> 
* **`array_2d[row,col]`**.

In [12]:
array_2d[2]

array([ 8,  9, 10, 11])

In [13]:
array_2d[5,2]

22

In [14]:
array_2d[5][2]

22

In [15]:
# 2D array slicing
array_2d[:2,:2]

array([[0, 1],
       [4, 5]])

In [16]:
array_2d[2:4,2:4] # inner slice

array([[10, 11],
       [14, 15]])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [17]:
# Lets create an array using arange()
array_1d = np.arange(0,10)
array_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Take a slice of the array and set it equal to some number, say 500.<br>

        array_1d[0:5] = 500 
this will **broadcast the value of 500 to the first 5 elements** of the array_1d

In [18]:
array_1d[0:5] = 500 
array_1d

array([500, 500, 500, 500, 500,   5,   6,   7,   8,   9])

In [19]:
# Lets create a 2D martix with ones
array_2d = np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
array_2d

array([[300., 300., 300., 300.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [21]:
# Lets create a simple 1-D array and broadcast to array_2d
array_2d + np.arange(0,4)

array([[300., 301., 302., 303.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [22]:
array_2d + 300

array([[600., 600., 600., 600.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.],
       [301., 301., 301., 301.]])