# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br>

# Installing NumPy

conda install numpy 


**Import NumPy**

In [2]:
import numpy as np

# Numpy Arrays

Numpy arrays essentially come in two flavors: <br>
* **Vectors:** Vectors are strictly 1-dimensional array
*  **Matrices:** Matrices are 2-dimensional (matrix can still have only one row or one column).

## Creating NumPy Arrays

### From Python data type (e.g. List, Tuple)

In [3]:
# Lets create a Python list. 
list1 = [-1,0,1]
list1, type(list1)

([-1, 0, 1], list)

To create a NumPy array, from a Python data structure, we use NumPy's array function. <br>
The NumPy's array function can be accessed by typing "np.array". <br>
We need to cast our Python data structure, my_list, as a parameter to the array function.<br>

In [4]:
my_array = np.array(list1) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [5]:
# Lets create and cast a list of list to generate 2-D array 
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

### Array creation using NumPy's Built-in methods

Most of the times, we use NumPy built-in methods to create arrays. These are much simpler and faster.

### `arange()`

* arange() is very much similar to Python function range() <br>
* Return evenly spaced values within a given interval. <br>


In [8]:
np.arange(0,10) # similar to range() in Python, not including 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

numpy.arange(start, stop, step, dtype)
* start - Start of an interval
* stop - End of an interval
* step - Spacing between values,default is 1
* dtype - Data type of resulting ndarray. If not given, data type of input is used


In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`
Return evenly spaced numbers over a specified interval.<br>

In [11]:
# start from 1 & end at 15 with 10 evenly spaced points b/w 1 to 15.
np.linspace(1, 15, 15)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [12]:
# Lets find the step size with "retstep" which returns the array and the step size
my_linspace = np.linspace(5, 15, 9, retstep=True)
my_linspace
# the step size here is 1.25

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [13]:
np.linspace(5, 25, 9, retstep=True)
#the step size is 2.5

(array([ 5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ]), 2.5)

***The main thing that we want to notice here is that***

* arange() takes 3rd argument as step size.<br>
* linspace() take 3rd argument as no of points we want.

### `zeros()` and  `ones()`

Generate arrays of zeros or ones

In [14]:
np.zeros(3)  # 1-D with 3 elements

array([0., 0., 0.])

In [15]:
np.zeros((5,5))  #(no_row, no_col) passing a tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(3)  

array([1., 1., 1.])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `eye()` 

* Return a 2-D array with **ones on the diagonal and zeros elsewhere.**


In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

We can also create arrays with random numbers using Numpy's built-in functions in Random module.<br>

### `rand()`
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [20]:
np.random.rand(3) # 1-D array with three elements

array([0.16830364, 0.76634067, 0.74268244])

In [21]:
np.random.rand(3,2) # row, col, note we are not passing a tuple here, each dimension as a separate argument

array([[0.24298182, 0.08914793],
       [0.93772003, 0.07247672],
       [0.44959282, 0.53097239]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.

In [22]:
np.random.randn(3)

array([0.39664239, 0.60689843, 0.60335192])

In [23]:
np.random.randn(4,4)

array([[-0.73009459,  0.06489327, -0.9352536 , -1.64524977],
       [ 0.09490535,  0.91941806,  2.48842382,  1.25620237],
       [ 0.23056291, -0.6179384 ,  1.14202846, -0.20766683],
       [-0.35801162, -0.22054492,  0.36675529,  0.93359331]])

### `randint()`
Return random integers from `low` (inclusive) to `high` (exclusive).

In [24]:
np.random.randint(1,100) #returns one random int, 1 inclusive, 100 exclusive

46

In [25]:
np.random.randint(1,100,10) #returns ten random int,

array([22, 41, 93,  8, 16, 13, 55, 10, 75, 20])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape(), max(), min(), argmax(), argmin()<br>

In [26]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16)
array_ranint = np.random.randint(0,100,10)

In [27]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
array_ranint

array([94, 71, 43, 30, 97, 84, 78, 93, 91, 24])

#### `Reshape()`
Returns an array containing the same data with a new shape.

In [29]:
array_arange.reshape(4,4) # any other num will give error

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### `max()` & `min()`
Useful methods for finding max or min values.

In [30]:
array_ranint

array([94, 71, 43, 30, 97, 84, 78, 93, 91, 24])

In [31]:
array_ranint.max()

97

In [32]:
array_ranint.min()

24

#### `argmax()` & `argmin()`
To find the index locations of max and min values in array

In [33]:
array_ranint.argmax() # index starts from 0

4

In [34]:
array_ranint.argmin()

9

### Attributes
* `size, shape, dtype` 

In [35]:
array_arange.shape

(16,)

In [36]:
# Size of the array 
array_arange.size

16

In [37]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [38]:
# Notice the two sets of brackets
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [39]:
array_arange.reshape(4,4).shape

(4, 4)

In [50]:
array_arange.reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [52]:
array_arange.dtype

dtype('int32')